[package]
name = "upload-file"
version = "0.1.0"
edition = "2021"

[dependencies]
anthropic-ai-sdk = { path = "../../../anthropic-ai-sdk" }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }