[package]
name = "anthropic-ai-sdk"
version = "0.2.27"
edition = "2024"
authors = ["Katsuhiro Honda<freewave3@gmail.com>"]
categories = ["api-bindings"]
description = "An unofficial Rust SDK for Anthropic's Claude AI API"
keywords = ["anthropic", "sdk", "ai"]
license = "MIT"
repository = "https://github.com/katsuhirohonda/anthropic-sdk-rs/tree/main/anthropic-ai-sdk"
rust-version = "1.85.0"

[features]
default = ["rustls-tls"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dependencies]
thiserror = { version = "2", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "multipart"] }
async-trait = { version = "0.1", default-features = false }
time = { version = "0.3", default-features = false, features = ["serde", "serde-well-known"] }
futures-util = { version = "0.3", default-features = false }
eventsource-stream = { version = "0.2", default-features = false }

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }
