[package]
name = "get-invite"
version = "0.1.0"
edition = "2024"

[dependencies]
anthropic-ai-sdk = { path = "../../../../anthropic-ai-sdk" }
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
